#version: "3.8"
#services:
#    # PHP Service
#    php:
#        build:
#            context: .
#            target: php
#            args:
#                - APP_ENV=${APP_ENV}
#        environment:
#            - APP_ENV=${APP_ENV}
#            - CONTAINER_ROLE=app
#        working_dir: /var/www
#        volumes:
#            - ./:/var/www
#        ports:
#            - 8000:8000
#        depends_on:
#            - database
#            - redis
#        container_name: app
#    # Database Server
#    database:
#        image: mysql:latest
#        ports:
#            - 3307:3306
#        environment:
#            - MYSQL_DATABASE=${DB_DATABASE}
#            - MYSQL_USER=${DB_USERNAME}
#            - MYSQL_PASSWORD=${DB_PASSWORD}
#            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#        volumes:
#            - db-data:/var/lib/mysql
#        container_name: db
#    # Redis Server
#    redis:
#        image: redis:alpine
#        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
#        ports:
#            - 6379:6379
#        container_name: redis
#volumes:
#    db-data: ~

version: '3'
services:
    app:
        build: .
        container_name: laravel_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    db:
        image: mysql:latest
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: kapal
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
